using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Konamiman.Nestor80.Assembler
{
    public partial class AssemblySourceProcessor
    {
        /* Instructions that need to be handled as special cases:
         * 
         * JR, DJNZ: Argument is an address, but generated opcode contains a 1 byte offset from current location pointer
         * LD (IX/Y+n),n: There's a second argument (placed at the last byte)
         * BIT/SET/RES n,R: n must evaluate to a number between 1 and 7
         * RST n: n must evaluate to one of 00h, 08h, 10h, 18h, 20h, 28h, 30h, 38h
         */
        Dictionary<string, ProcessorInstruction[]> Z80Instructions = new Dictionary<string, ProcessorInstruction[]> {
            { "ADC", new ProcessorInstruction[] {
                new ProcessorInstruction( "ADC", "A", "(HL)", new byte[] { 0x8e } ),
                new ProcessorInstruction( "ADC", "A", "(IX+n)", new byte[] { 0xdd, 0x8e, 0 }, 2, 1 ),
                new ProcessorInstruction( "ADC", "A", "(IY+n)", new byte[] { 0xfd, 0x8e, 0 }, 2, 1 ),
                new ProcessorInstruction( "ADC", "A", "A", new byte[] { 0x8f } ),
                new ProcessorInstruction( "ADC", "A", "B", new byte[] { 0x88 } ),
                new ProcessorInstruction( "ADC", "A", "C", new byte[] { 0x89 } ),
                new ProcessorInstruction( "ADC", "A", "D", new byte[] { 0x8a } ),
                new ProcessorInstruction( "ADC", "A", "E", new byte[] { 0x8b } ),
                new ProcessorInstruction( "ADC", "A", "H", new byte[] { 0x8c } ),
                new ProcessorInstruction( "ADC", "A", "L", new byte[] { 0x8d } ),
                new ProcessorInstruction( "ADC", "A", "n", new byte[] { 0xce, 0 }, 1, 1 ),
                new ProcessorInstruction( "ADC", "HL", "BC", new byte[] { 0xed, 0x4a } ),
                new ProcessorInstruction( "ADC", "HL", "DE", new byte[] { 0xed, 0x5a } ),
                new ProcessorInstruction( "ADC", "HL", "HL", new byte[] { 0xed, 0x6a } ),
                new ProcessorInstruction( "ADC", "HL", "SP", new byte[] { 0xed, 0x7a } ),
                new ProcessorInstruction( "ADC", "A", "IXH", new byte[] { 0xdd, 0x8c }, 0, 0, true ),
                new ProcessorInstruction( "ADC", "A", "IXL", new byte[] { 0xdd, 0x8d }, 0, 0, true ),
                new ProcessorInstruction( "ADC", "A", "IYH", new byte[] { 0xfd, 0x8c }, 0, 0, true ),
                new ProcessorInstruction( "ADC", "A", "IYL", new byte[] { 0xfd, 0x8d }, 0, 0, true ) } },
            { "ADD", new ProcessorInstruction[] {
                new ProcessorInstruction( "ADD", "A", "(HL)", new byte[] { 0x86 } ),
                new ProcessorInstruction( "ADD", "A", "(IX+n)", new byte[] { 0xdd, 0x86, 0 }, 2, 1 ),
                new ProcessorInstruction( "ADD", "A", "(IY+n)", new byte[] { 0xfd, 0x86, 0 }, 2, 1 ),
                new ProcessorInstruction( "ADD", "A", "A", new byte[] { 0x87 } ),
                new ProcessorInstruction( "ADD", "A", "B", new byte[] { 0x80 } ),
                new ProcessorInstruction( "ADD", "A", "C", new byte[] { 0x81 } ),
                new ProcessorInstruction( "ADD", "A", "D", new byte[] { 0x82 } ),
                new ProcessorInstruction( "ADD", "A", "E", new byte[] { 0x83 } ),
                new ProcessorInstruction( "ADD", "A", "H", new byte[] { 0x84 } ),
                new ProcessorInstruction( "ADD", "A", "L", new byte[] { 0x85 } ),
                new ProcessorInstruction( "ADD", "A", "n", new byte[] { 0xc6, 0 }, 1, 1 ),
                new ProcessorInstruction( "ADD", "HL", "BC", new byte[] { 0x09 } ),
                new ProcessorInstruction( "ADD", "HL", "DE", new byte[] { 0x19 } ),
                new ProcessorInstruction( "ADD", "HL", "HL", new byte[] { 0x29 } ),
                new ProcessorInstruction( "ADD", "HL", "SP", new byte[] { 0x39 } ),
                new ProcessorInstruction( "ADD", "IX", "BC", new byte[] { 0xdd, 0x09 } ),
                new ProcessorInstruction( "ADD", "IX", "DE", new byte[] { 0xdd, 0x19 } ),
                new ProcessorInstruction( "ADD", "IX", "IX", new byte[] { 0xdd, 0x29 } ),
                new ProcessorInstruction( "ADD", "IX", "SP", new byte[] { 0xdd, 0x39 } ),
                new ProcessorInstruction( "ADD", "IY", "BC", new byte[] { 0xfd, 0x09 } ),
                new ProcessorInstruction( "ADD", "IY", "DE", new byte[] { 0xfd, 0x19 } ),
                new ProcessorInstruction( "ADD", "IY", "IY", new byte[] { 0xfd, 0x29 } ),
                new ProcessorInstruction( "ADD", "IY", "SP", new byte[] { 0xfd, 0x39 } ),
                new ProcessorInstruction( "ADD", "A", "IXH", new byte[] { 0xdd, 0x84 }, 0, 0, true ),
                new ProcessorInstruction( "ADD", "A", "IXL", new byte[] { 0xdd, 0x85 }, 0, 0, true ),
                new ProcessorInstruction( "ADD", "A", "IYH", new byte[] { 0xfd, 0x84 }, 0, 0, true ),
                new ProcessorInstruction( "ADD", "A", "IYL", new byte[] { 0xfd, 0x85 }, 0, 0, true ) } },
            { "AND", new ProcessorInstruction[] {
                new ProcessorInstruction( "AND", "(HL)", null, new byte[] { 0xa6 } ),
                new ProcessorInstruction( "AND", "(IX+n)", null, new byte[] { 0xdd, 0xa6, 0 }, 2, 1 ),
                new ProcessorInstruction( "AND", "(IY+n)", null, new byte[] { 0xfd, 0xa6, 0 }, 2, 1 ),
                new ProcessorInstruction( "AND", "A", null, new byte[] { 0xa7 } ),
                new ProcessorInstruction( "AND", "B", null, new byte[] { 0xa0 } ),
                new ProcessorInstruction( "AND", "C", null, new byte[] { 0xa1 } ),
                new ProcessorInstruction( "AND", "D", null, new byte[] { 0xa2 } ),
                new ProcessorInstruction( "AND", "E", null, new byte[] { 0xa3 } ),
                new ProcessorInstruction( "AND", "H", null, new byte[] { 0xa4 } ),
                new ProcessorInstruction( "AND", "L", null, new byte[] { 0xa5 } ),
                new ProcessorInstruction( "AND", "n", null, new byte[] { 0xe6, 0 }, 1, 1 ),
                new ProcessorInstruction( "AND", "IXH", null, new byte[] { 0xdd, 0xa4 }, 0, 0, true ),
                new ProcessorInstruction( "AND", "IXL", null, new byte[] { 0xdd, 0xa5 }, 0, 0, true ),
                new ProcessorInstruction( "AND", "IYH", null, new byte[] { 0xfd, 0xa4 }, 0, 0, true ),
                new ProcessorInstruction( "AND", "IYL", null, new byte[] { 0xfd, 0xa5 }, 0, 0, true ) } },
            { "BIT", new ProcessorInstruction[] {
                new ProcessorInstruction( "BIT", "0", "(HL)", new byte[] { 0xcb, 0x46 } ),
                new ProcessorInstruction( "BIT", "0", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x46 } ),
                new ProcessorInstruction( "BIT", "0", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x46 } ),
                new ProcessorInstruction( "BIT", "0", "A", new byte[] { 0xcb, 0x47 } ),
                new ProcessorInstruction( "BIT", "0", "B", new byte[] { 0xcb, 0x40 } ),
                new ProcessorInstruction( "BIT", "0", "C", new byte[] { 0xcb, 0x41 } ),
                new ProcessorInstruction( "BIT", "0", "D", new byte[] { 0xcb, 0x42 } ),
                new ProcessorInstruction( "BIT", "0", "E", new byte[] { 0xcb, 0x43 } ),
                new ProcessorInstruction( "BIT", "0", "H", new byte[] { 0xcb, 0x44 } ),
                new ProcessorInstruction( "BIT", "0", "L", new byte[] { 0xcb, 0x45 } ),
                new ProcessorInstruction( "BIT", "1", "(HL)", new byte[] { 0xcb, 0x4e } ),
                new ProcessorInstruction( "BIT", "1", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x4e } ),
                new ProcessorInstruction( "BIT", "1", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x4e } ),
                new ProcessorInstruction( "BIT", "1", "A", new byte[] { 0xcb, 0x4f } ),
                new ProcessorInstruction( "BIT", "1", "B", new byte[] { 0xcb, 0x48 } ),
                new ProcessorInstruction( "BIT", "1", "C", new byte[] { 0xcb, 0x49 } ),
                new ProcessorInstruction( "BIT", "1", "D", new byte[] { 0xcb, 0x4a } ),
                new ProcessorInstruction( "BIT", "1", "E", new byte[] { 0xcb, 0x4b } ),
                new ProcessorInstruction( "BIT", "1", "H", new byte[] { 0xcb, 0x4c } ),
                new ProcessorInstruction( "BIT", "1", "L", new byte[] { 0xcb, 0x4d } ),
                new ProcessorInstruction( "BIT", "2", "(HL)", new byte[] { 0xcb, 0x56 } ),
                new ProcessorInstruction( "BIT", "2", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x56 } ),
                new ProcessorInstruction( "BIT", "2", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x56 } ),
                new ProcessorInstruction( "BIT", "2", "A", new byte[] { 0xcb, 0x57 } ),
                new ProcessorInstruction( "BIT", "2", "B", new byte[] { 0xcb, 0x50 } ),
                new ProcessorInstruction( "BIT", "2", "C", new byte[] { 0xcb, 0x51 } ),
                new ProcessorInstruction( "BIT", "2", "D", new byte[] { 0xcb, 0x52 } ),
                new ProcessorInstruction( "BIT", "2", "E", new byte[] { 0xcb, 0x53 } ),
                new ProcessorInstruction( "BIT", "2", "H", new byte[] { 0xcb, 0x54 } ),
                new ProcessorInstruction( "BIT", "2", "L", new byte[] { 0xcb, 0x55 } ),
                new ProcessorInstruction( "BIT", "3", "(HL)", new byte[] { 0xcb, 0x5e } ),
                new ProcessorInstruction( "BIT", "3", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x5e } ),
                new ProcessorInstruction( "BIT", "3", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x5e } ),
                new ProcessorInstruction( "BIT", "3", "A", new byte[] { 0xcb, 0x5f } ),
                new ProcessorInstruction( "BIT", "3", "B", new byte[] { 0xcb, 0x58 } ),
                new ProcessorInstruction( "BIT", "3", "C", new byte[] { 0xcb, 0x59 } ),
                new ProcessorInstruction( "BIT", "3", "D", new byte[] { 0xcb, 0x5a } ),
                new ProcessorInstruction( "BIT", "3", "E", new byte[] { 0xcb, 0x5b } ),
                new ProcessorInstruction( "BIT", "3", "H", new byte[] { 0xcb, 0x5c } ),
                new ProcessorInstruction( "BIT", "3", "L", new byte[] { 0xcb, 0x5d } ),
                new ProcessorInstruction( "BIT", "4", "(HL)", new byte[] { 0xcb, 0x66 } ),
                new ProcessorInstruction( "BIT", "4", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x66 } ),
                new ProcessorInstruction( "BIT", "4", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x66 } ),
                new ProcessorInstruction( "BIT", "4", "A", new byte[] { 0xcb, 0x67 } ),
                new ProcessorInstruction( "BIT", "4", "B", new byte[] { 0xcb, 0x60 } ),
                new ProcessorInstruction( "BIT", "4", "C", new byte[] { 0xcb, 0x61 } ),
                new ProcessorInstruction( "BIT", "4", "D", new byte[] { 0xcb, 0x62 } ),
                new ProcessorInstruction( "BIT", "4", "E", new byte[] { 0xcb, 0x63 } ),
                new ProcessorInstruction( "BIT", "4", "H", new byte[] { 0xcb, 0x64 } ),
                new ProcessorInstruction( "BIT", "4", "L", new byte[] { 0xcb, 0x65 } ),
                new ProcessorInstruction( "BIT", "5", "(HL)", new byte[] { 0xcb, 0x6e } ),
                new ProcessorInstruction( "BIT", "5", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x6e } ),
                new ProcessorInstruction( "BIT", "5", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x6e } ),
                new ProcessorInstruction( "BIT", "5", "A", new byte[] { 0xcb, 0x6f } ),
                new ProcessorInstruction( "BIT", "5", "B", new byte[] { 0xcb, 0x68 } ),
                new ProcessorInstruction( "BIT", "5", "C", new byte[] { 0xcb, 0x69 } ),
                new ProcessorInstruction( "BIT", "5", "D", new byte[] { 0xcb, 0x6a } ),
                new ProcessorInstruction( "BIT", "5", "E", new byte[] { 0xcb, 0x6b } ),
                new ProcessorInstruction( "BIT", "5", "H", new byte[] { 0xcb, 0x6c } ),
                new ProcessorInstruction( "BIT", "5", "L", new byte[] { 0xcb, 0x6d } ),
                new ProcessorInstruction( "BIT", "6", "(HL)", new byte[] { 0xcb, 0x76 } ),
                new ProcessorInstruction( "BIT", "6", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x76 } ),
                new ProcessorInstruction( "BIT", "6", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x76 } ),
                new ProcessorInstruction( "BIT", "6", "A", new byte[] { 0xcb, 0x77 } ),
                new ProcessorInstruction( "BIT", "6", "B", new byte[] { 0xcb, 0x70 } ),
                new ProcessorInstruction( "BIT", "6", "C", new byte[] { 0xcb, 0x71 } ),
                new ProcessorInstruction( "BIT", "6", "D", new byte[] { 0xcb, 0x72 } ),
                new ProcessorInstruction( "BIT", "6", "E", new byte[] { 0xcb, 0x73 } ),
                new ProcessorInstruction( "BIT", "6", "H", new byte[] { 0xcb, 0x74 } ),
                new ProcessorInstruction( "BIT", "6", "L", new byte[] { 0xcb, 0x75 } ),
                new ProcessorInstruction( "BIT", "7", "(HL)", new byte[] { 0xcb, 0x7e } ),
                new ProcessorInstruction( "BIT", "7", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x7e } ),
                new ProcessorInstruction( "BIT", "7", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x7e } ),
                new ProcessorInstruction( "BIT", "7", "A", new byte[] { 0xcb, 0x7f } ),
                new ProcessorInstruction( "BIT", "7", "B", new byte[] { 0xcb, 0x78 } ),
                new ProcessorInstruction( "BIT", "7", "C", new byte[] { 0xcb, 0x79 } ),
                new ProcessorInstruction( "BIT", "7", "D", new byte[] { 0xcb, 0x7a } ),
                new ProcessorInstruction( "BIT", "7", "E", new byte[] { 0xcb, 0x7b } ),
                new ProcessorInstruction( "BIT", "7", "H", new byte[] { 0xcb, 0x7c } ),
                new ProcessorInstruction( "BIT", "7", "L", new byte[] { 0xcb, 0x7d } ) } },
            { "CALL", new ProcessorInstruction[] {
                new ProcessorInstruction( "CALL", "C", "nn", new byte[] { 0xdc, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "M", "nn", new byte[] { 0xfc, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "nc", "nn", new byte[] { 0xd4, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "nc", "nn", new byte[] { 0xd4, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "nn", null, new byte[] { 0xcd, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "nz", "nn", new byte[] { 0xc4, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "PE", "nn", new byte[] { 0xec, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "PO", "nn", new byte[] { 0xe4, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "CALL", "Z", "nn", new byte[] { 0xcc, 0, 0 }, 1, 2 ) } },
            { "CCF", new ProcessorInstruction[] {
                new ProcessorInstruction( "CCF", null, null, new byte[] { 0x3f } ) } },
            { "CP", new ProcessorInstruction[] {
                new ProcessorInstruction( "CP", "(HL)", null, new byte[] { 0xbe } ),
                new ProcessorInstruction( "CP", "(IX+n)", null, new byte[] { 0xdd, 0xbe, 0 }, 2, 1 ),
                new ProcessorInstruction( "CP", "(IY+n)", null, new byte[] { 0xfd, 0xbe, 0 }, 2, 1 ),
                new ProcessorInstruction( "CP", "A", null, new byte[] { 0xbf } ),
                new ProcessorInstruction( "CP", "B", null, new byte[] { 0xb8 } ),
                new ProcessorInstruction( "CP", "C", null, new byte[] { 0xb9 } ),
                new ProcessorInstruction( "CP", "D", null, new byte[] { 0xba } ),
                new ProcessorInstruction( "CP", "E", null, new byte[] { 0xbb } ),
                new ProcessorInstruction( "CP", "H", null, new byte[] { 0xbc } ),
                new ProcessorInstruction( "CP", "L", null, new byte[] { 0xbd } ),
                new ProcessorInstruction( "CP", "n", null, new byte[] { 0xfe, 0 }, 1, 1 ),
                new ProcessorInstruction( "CP", "IXH", null, new byte[] { 0xdd, 0xbc }, 0, 0, true ),
                new ProcessorInstruction( "CP", "IXL", null, new byte[] { 0xdd, 0xbd }, 0, 0, true ),
                new ProcessorInstruction( "CP", "IYH", null, new byte[] { 0xfd, 0xbc }, 0, 0, true ),
                new ProcessorInstruction( "CP", "IYL", null, new byte[] { 0xfd, 0xbd }, 0, 0, true ) } },
            { "CPD", new ProcessorInstruction[] {
                new ProcessorInstruction( "CPD", null, null, new byte[] { 0xed, 0xa9 } ) } },
            { "CPDR", new ProcessorInstruction[] {
                new ProcessorInstruction( "CPDR", null, null, new byte[] { 0xed, 0xb9 } ) } },
            { "CPI", new ProcessorInstruction[] {
                new ProcessorInstruction( "CPI", null, null, new byte[] { 0xed, 0xa1 } ) } },
            { "CPIR", new ProcessorInstruction[] {
                new ProcessorInstruction( "CPIR", null, null, new byte[] { 0xed, 0xb1 } ) } },
            { "CPL", new ProcessorInstruction[] {
                new ProcessorInstruction( "CPL", null, null, new byte[] { 0x2f } ) } },
            { "DAA", new ProcessorInstruction[] {
                new ProcessorInstruction( "DAA", null, null, new byte[] { 0x27 } ) } },
            { "DEC", new ProcessorInstruction[] {
                new ProcessorInstruction( "DEC", "(HL)", null, new byte[] { 0x35 } ),
                new ProcessorInstruction( "DEC", "(IX+n)", null, new byte[] { 0xdd, 0x35, 0 }, 2, 1 ),
                new ProcessorInstruction( "DEC", "(IY+n)", null, new byte[] { 0xfd, 0x35, 0 }, 2, 1 ),
                new ProcessorInstruction( "DEC", "A", null, new byte[] { 0x3d } ),
                new ProcessorInstruction( "DEC", "B", null, new byte[] { 0x05 } ),
                new ProcessorInstruction( "DEC", "BC", null, new byte[] { 0x0b } ),
                new ProcessorInstruction( "DEC", "C", null, new byte[] { 0x0d } ),
                new ProcessorInstruction( "DEC", "D", null, new byte[] { 0x15 } ),
                new ProcessorInstruction( "DEC", "DE", null, new byte[] { 0x1b } ),
                new ProcessorInstruction( "DEC", "E", null, new byte[] { 0x1d } ),
                new ProcessorInstruction( "DEC", "H", null, new byte[] { 0x25 } ),
                new ProcessorInstruction( "DEC", "HL", null, new byte[] { 0x2b } ),
                new ProcessorInstruction( "DEC", "IX", null, new byte[] { 0xdd, 0x2b } ),
                new ProcessorInstruction( "DEC", "IY", null, new byte[] { 0xfd, 0x2b } ),
                new ProcessorInstruction( "DEC", "L", null, new byte[] { 0x2d } ),
                new ProcessorInstruction( "DEC", "SP", null, new byte[] { 0x3b } ),
                new ProcessorInstruction( "DEC", "IXH", null, new byte[] { 0xdd, 0x25 }, 0, 0, true ),
                new ProcessorInstruction( "DEC", "IXL", null, new byte[] { 0xdd, 0x2d }, 0, 0, true ),
                new ProcessorInstruction( "DEC", "IYH", null, new byte[] { 0xfd, 0x25 }, 0, 0, true ),
                new ProcessorInstruction( "DEC", "IYL", null, new byte[] { 0xfd, 0x2d }, 0, 0, true ) } },
            { "DI", new ProcessorInstruction[] {
                new ProcessorInstruction( "DI", null, null, new byte[] { 0xf3 } ) } },
            { "DJNZ", new ProcessorInstruction[] {
                new ProcessorInstruction( "DJNZ", "n", null, new byte[] { 0x10, 0 }, 1, 1 ) } },
            { "EI", new ProcessorInstruction[] {
                new ProcessorInstruction( "EI", null, null, new byte[] { 0xfb } ) } },
            { "EX", new ProcessorInstruction[] {
                new ProcessorInstruction( "EX", "(SP)", "HL", new byte[] { 0xe3 } ),
                new ProcessorInstruction( "EX", "(SP)", "IX", new byte[] { 0xdd, 0xe3 } ),
                new ProcessorInstruction( "EX", "(SP)", "IY", new byte[] { 0xfd, 0xe3 } ),
                new ProcessorInstruction( "EX", "AF", "AF'", new byte[] { 0x08 } ),
                new ProcessorInstruction( "EX", "DE", "HL", new byte[] { 0xeb } ) } },
            { "EXX", new ProcessorInstruction[] {
                new ProcessorInstruction( "EXX", null, null, new byte[] { 0xd9 } ) } },
            { "HALT", new ProcessorInstruction[] {
                new ProcessorInstruction( "HALT", null, null, new byte[] { 0x76 } ) } },
            { "IM", new ProcessorInstruction[] {
                new ProcessorInstruction( "IM", "0", null, new byte[] { 0xed, 0x46 } ),
                new ProcessorInstruction( "IM", "1", null, new byte[] { 0xed, 0x56 } ),
                new ProcessorInstruction( "IM", "2", null, new byte[] { 0xed, 0x5e } ) } },
            { "IN", new ProcessorInstruction[] {
                new ProcessorInstruction( "IN", "A", "(C)", new byte[] { 0xed, 0x78 } ),
                new ProcessorInstruction( "IN", "A", "(n)", new byte[] { 0xdb, 0 }, 1, 1 ),
                new ProcessorInstruction( "IN", "B", "(C)", new byte[] { 0xed, 0x40 } ),
                new ProcessorInstruction( "IN", "C", "(C)", new byte[] { 0xed, 0x48 } ),
                new ProcessorInstruction( "IN", "D", "(C)", new byte[] { 0xed, 0x50 } ),
                new ProcessorInstruction( "IN", "E", "(C)", new byte[] { 0xed, 0x58 } ),
                new ProcessorInstruction( "IN", "H", "(C)", new byte[] { 0xed, 0x60 } ),
                new ProcessorInstruction( "IN", "L", "(C)", new byte[] { 0xed, 0x68 } ),
                new ProcessorInstruction( "IN", "F", "(C)", new byte[] { 0xed, 0x70 }, 0, 0, true ) } },
            { "INC", new ProcessorInstruction[] {
                new ProcessorInstruction( "INC", "(HL)", null, new byte[] { 0x34 } ),
                new ProcessorInstruction( "INC", "(IX+n)", null, new byte[] { 0xdd, 0x34, 0 }, 2, 1 ),
                new ProcessorInstruction( "INC", "(IY+n)", null, new byte[] { 0xfd, 0x34, 0 }, 2, 1 ),
                new ProcessorInstruction( "INC", "A", null, new byte[] { 0x3c } ),
                new ProcessorInstruction( "INC", "B", null, new byte[] { 0x04 } ),
                new ProcessorInstruction( "INC", "BC", null, new byte[] { 0x03 } ),
                new ProcessorInstruction( "INC", "C", null, new byte[] { 0x0c } ),
                new ProcessorInstruction( "INC", "D", null, new byte[] { 0x14 } ),
                new ProcessorInstruction( "INC", "DE", null, new byte[] { 0x13 } ),
                new ProcessorInstruction( "INC", "E", null, new byte[] { 0x1c } ),
                new ProcessorInstruction( "INC", "H", null, new byte[] { 0x24 } ),
                new ProcessorInstruction( "INC", "HL", null, new byte[] { 0x23 } ),
                new ProcessorInstruction( "INC", "IX", null, new byte[] { 0xdd, 0x23 } ),
                new ProcessorInstruction( "INC", "IY", null, new byte[] { 0xfd, 0x23 } ),
                new ProcessorInstruction( "INC", "L", null, new byte[] { 0x2c } ),
                new ProcessorInstruction( "INC", "SP", null, new byte[] { 0x33 } ),
                new ProcessorInstruction( "INC", "IXH", null, new byte[] { 0xdd, 0x24 }, 0, 0, true ),
                new ProcessorInstruction( "INC", "IXL", null, new byte[] { 0xdd, 0x2c }, 0, 0, true ),
                new ProcessorInstruction( "INC", "IYH", null, new byte[] { 0xfd, 0x24 }, 0, 0, true ),
                new ProcessorInstruction( "INC", "IYL", null, new byte[] { 0xfd, 0x2c }, 0, 0, true ) } },
            { "IND", new ProcessorInstruction[] {
                new ProcessorInstruction( "IND", null, null, new byte[] { 0xed, 0xaa } ) } },
            { "INDR", new ProcessorInstruction[] {
                new ProcessorInstruction( "INDR", null, null, new byte[] { 0xed, 0xba } ) } },
            { "INI", new ProcessorInstruction[] {
                new ProcessorInstruction( "INI", null, null, new byte[] { 0xed, 0xa2 } ) } },
            { "INIR", new ProcessorInstruction[] {
                new ProcessorInstruction( "INIR", null, null, new byte[] { 0xed, 0xb2 } ) } },
            { "JP", new ProcessorInstruction[] {
                new ProcessorInstruction( "JP", "nn", null, new byte[] { 0xc3, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "(HL)", null, new byte[] { 0xe9 } ),
                new ProcessorInstruction( "JP", "(IX)", null, new byte[] { 0xdd, 0xe9 } ),
                new ProcessorInstruction( "JP", "(IY)", null, new byte[] { 0xfd, 0xe9 } ),
                new ProcessorInstruction( "JP", "C", "nn", new byte[] { 0xda, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "M", "nn", new byte[] { 0xfa, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "nc", "nn", new byte[] { 0xd2, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "nz", "nn", new byte[] { 0xc2, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "P", "nn", new byte[] { 0xf2, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "PE", "nn", new byte[] { 0xea, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "PO", "nn", new byte[] { 0xe2, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "JP", "Z", "nn", new byte[] { 0xca, 0, 0 }, 1, 2 ) } },
            { "JR", new ProcessorInstruction[] {
                new ProcessorInstruction( "JR", "n", null, new byte[] { 0x18, 0 }, 1, 1 ),
                new ProcessorInstruction( "JR", "C", "n", new byte[] { 0x38, 0 }, 1, 1 ),
                new ProcessorInstruction( "JR", "nc", "n", new byte[] { 0x30, 0 }, 1, 1 ),
                new ProcessorInstruction( "JR", "nz", "n", new byte[] { 0x20, 0 }, 1, 1 ),
                new ProcessorInstruction( "JR", "Z", "n", new byte[] { 0x28, 0 }, 1, 1 ) } },
            { "LD", new ProcessorInstruction[] {
                new ProcessorInstruction( "LD", "(BC)", "A", new byte[] { 0x02 } ),
                new ProcessorInstruction( "LD", "(DE)", "A", new byte[] { 0x12 } ),
                new ProcessorInstruction( "LD", "(HL)", "A", new byte[] { 0x77 } ),
                new ProcessorInstruction( "LD", "(HL)", "B", new byte[] { 0x70 } ),
                new ProcessorInstruction( "LD", "(HL)", "C", new byte[] { 0x71 } ),
                new ProcessorInstruction( "LD", "(HL)", "D", new byte[] { 0x72 } ),
                new ProcessorInstruction( "LD", "(HL)", "E", new byte[] { 0x73 } ),
                new ProcessorInstruction( "LD", "(HL)", "H", new byte[] { 0x74 } ),
                new ProcessorInstruction( "LD", "(HL)", "L", new byte[] { 0x75 } ),
                new ProcessorInstruction( "LD", "(HL)", "n", new byte[] { 0x36, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "A", new byte[] { 0xdd, 0x77, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "B", new byte[] { 0xdd, 0x70, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "C", new byte[] { 0xdd, 0x71, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "D", new byte[] { 0xdd, 0x72, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "E", new byte[] { 0xdd, 0x73, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "H", new byte[] { 0xdd, 0x74, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "L", new byte[] { 0xdd, 0x75, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IX+n)", "n", new byte[] { 0xdd, 0x36, 0, 0x0 } ),
                new ProcessorInstruction( "LD", "(IY+n)", "A", new byte[] { 0xfd, 0x77, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "B", new byte[] { 0xfd, 0x70, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "C", new byte[] { 0xfd, 0x71, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "D", new byte[] { 0xfd, 0x72, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "E", new byte[] { 0xfd, 0x73, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "H", new byte[] { 0xfd, 0x74, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "L", new byte[] { 0xfd, 0x75, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "(IY+n)", "n", new byte[] { 0xfd, 0x36, 0, 0x0 } ),
                new ProcessorInstruction( "LD", "(nn)", "A", new byte[] { 0x32, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "BC", new byte[] { 0xed, 0x43, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "DE", new byte[] { 0xed, 0x53, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "HL", new byte[] { 0x22, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "IX", new byte[] { 0xdd, 0x22, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "IY", new byte[] { 0xfd, 0x22, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "(nn)", "SP", new byte[] { 0xed, 0x73, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "A", "(BC)", new byte[] { 0x0a } ),
                new ProcessorInstruction( "LD", "A", "(DE)", new byte[] { 0x1a } ),
                new ProcessorInstruction( "LD", "A", "(HL)", new byte[] { 0x7e } ),
                new ProcessorInstruction( "LD", "A", "(IX+n)", new byte[] { 0xdd, 0x7e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "A", "(IY+n)", new byte[] { 0xfd, 0x7e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "A", "(nn)", new byte[] { 0x3a, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "A", "A", new byte[] { 0x7f } ),
                new ProcessorInstruction( "LD", "A", "B", new byte[] { 0x78 } ),
                new ProcessorInstruction( "LD", "A", "C", new byte[] { 0x79 } ),
                new ProcessorInstruction( "LD", "A", "D", new byte[] { 0x7a } ),
                new ProcessorInstruction( "LD", "A", "E", new byte[] { 0x7b } ),
                new ProcessorInstruction( "LD", "A", "H", new byte[] { 0x7c } ),
                new ProcessorInstruction( "LD", "A", "I", new byte[] { 0xed, 0x57 } ),
                new ProcessorInstruction( "LD", "A", "L", new byte[] { 0x7d } ),
                new ProcessorInstruction( "LD", "A", "n", new byte[] { 0x3e, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "B", "(HL)", new byte[] { 0x46 } ),
                new ProcessorInstruction( "LD", "B", "(IX+n)", new byte[] { 0xdd, 0x46, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "B", "(IY+n)", new byte[] { 0xfd, 0x46, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "B", "A", new byte[] { 0x47 } ),
                new ProcessorInstruction( "LD", "B", "B", new byte[] { 0x40 } ),
                new ProcessorInstruction( "LD", "B", "C", new byte[] { 0x41 } ),
                new ProcessorInstruction( "LD", "B", "D", new byte[] { 0x42 } ),
                new ProcessorInstruction( "LD", "B", "E", new byte[] { 0x43 } ),
                new ProcessorInstruction( "LD", "B", "H", new byte[] { 0x44 } ),
                new ProcessorInstruction( "LD", "B", "L", new byte[] { 0x45 } ),
                new ProcessorInstruction( "LD", "B", "n", new byte[] { 0x06, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "BC", "(nn)", new byte[] { 0xed, 0x4b, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "BC", "nn", new byte[] { 0x01, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "C", "(HL)", new byte[] { 0x4e } ),
                new ProcessorInstruction( "LD", "C", "(IX+n)", new byte[] { 0xdd, 0x4e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "C", "(IY+n)", new byte[] { 0xfd, 0x4e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "C", "A", new byte[] { 0x4f } ),
                new ProcessorInstruction( "LD", "C", "B", new byte[] { 0x48 } ),
                new ProcessorInstruction( "LD", "C", "C", new byte[] { 0x49 } ),
                new ProcessorInstruction( "LD", "C", "D", new byte[] { 0x4a } ),
                new ProcessorInstruction( "LD", "C", "E", new byte[] { 0x4b } ),
                new ProcessorInstruction( "LD", "C", "H", new byte[] { 0x4c } ),
                new ProcessorInstruction( "LD", "C", "L", new byte[] { 0x4d } ),
                new ProcessorInstruction( "LD", "C", "n", new byte[] { 0x0e, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "D", "(HL)", new byte[] { 0x56 } ),
                new ProcessorInstruction( "LD", "D", "(IX+n)", new byte[] { 0xdd, 0x56, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "D", "(IY+n)", new byte[] { 0xfd, 0x56, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "D", "A", new byte[] { 0x57 } ),
                new ProcessorInstruction( "LD", "D", "B", new byte[] { 0x50 } ),
                new ProcessorInstruction( "LD", "D", "C", new byte[] { 0x51 } ),
                new ProcessorInstruction( "LD", "D", "D", new byte[] { 0x52 } ),
                new ProcessorInstruction( "LD", "D", "E", new byte[] { 0x53 } ),
                new ProcessorInstruction( "LD", "D", "H", new byte[] { 0x54 } ),
                new ProcessorInstruction( "LD", "D", "L", new byte[] { 0x55 } ),
                new ProcessorInstruction( "LD", "D", "n", new byte[] { 0x16, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "DE", "(nn)", new byte[] { 0xed, 0x5b, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "DE", "nn", new byte[] { 0x11, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "E", "(HL)", new byte[] { 0x5e } ),
                new ProcessorInstruction( "LD", "E", "(IX+n)", new byte[] { 0xdd, 0x5e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "E", "(IY+n)", new byte[] { 0xfd, 0x5e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "E", "A", new byte[] { 0x5f } ),
                new ProcessorInstruction( "LD", "E", "B", new byte[] { 0x58 } ),
                new ProcessorInstruction( "LD", "E", "C", new byte[] { 0x59 } ),
                new ProcessorInstruction( "LD", "E", "D", new byte[] { 0x5a } ),
                new ProcessorInstruction( "LD", "E", "E", new byte[] { 0x5b } ),
                new ProcessorInstruction( "LD", "E", "H", new byte[] { 0x5c } ),
                new ProcessorInstruction( "LD", "E", "L", new byte[] { 0x5d } ),
                new ProcessorInstruction( "LD", "E", "n", new byte[] { 0x1e, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "H", "(HL)", new byte[] { 0x66 } ),
                new ProcessorInstruction( "LD", "H", "(IX+n)", new byte[] { 0xdd, 0x66, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "H", "(IY+n)", new byte[] { 0xfd, 0x66, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "H", "A", new byte[] { 0x67 } ),
                new ProcessorInstruction( "LD", "H", "B", new byte[] { 0x60 } ),
                new ProcessorInstruction( "LD", "H", "C", new byte[] { 0x61 } ),
                new ProcessorInstruction( "LD", "H", "D", new byte[] { 0x62 } ),
                new ProcessorInstruction( "LD", "H", "E", new byte[] { 0x63 } ),
                new ProcessorInstruction( "LD", "H", "H", new byte[] { 0x64 } ),
                new ProcessorInstruction( "LD", "H", "L", new byte[] { 0x65 } ),
                new ProcessorInstruction( "LD", "H", "n", new byte[] { 0x26, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "HL", "(nn)", new byte[] { 0x2a, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "HL", "nn", new byte[] { 0x21, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "I", "A", new byte[] { 0xed, 0x47 } ),
                new ProcessorInstruction( "LD", "IX", "(nn)", new byte[] { 0xdd, 0x2a, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "IX", "nn", new byte[] { 0xdd, 0x21, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "IY", "(nn)", new byte[] { 0xfd, 0x2a, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "IY", "nn", new byte[] { 0xfd, 0x21, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "L", "(HL)", new byte[] { 0x6e } ),
                new ProcessorInstruction( "LD", "L", "(IX+n)", new byte[] { 0xdd, 0x6e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "L", "(IY+n)", new byte[] { 0xfd, 0x6e, 0 }, 2, 1 ),
                new ProcessorInstruction( "LD", "L", "A", new byte[] { 0x6f } ),
                new ProcessorInstruction( "LD", "L", "B", new byte[] { 0x68 } ),
                new ProcessorInstruction( "LD", "L", "C", new byte[] { 0x69 } ),
                new ProcessorInstruction( "LD", "L", "D", new byte[] { 0x6a } ),
                new ProcessorInstruction( "LD", "L", "E", new byte[] { 0x6b } ),
                new ProcessorInstruction( "LD", "L", "H", new byte[] { 0x6c } ),
                new ProcessorInstruction( "LD", "L", "L", new byte[] { 0x6d } ),
                new ProcessorInstruction( "LD", "L", "n", new byte[] { 0x2e, 0 }, 1, 1 ),
                new ProcessorInstruction( "LD", "SP", "(nn)", new byte[] { 0xed, 0x7b, 0, 0 }, 2, 2 ),
                new ProcessorInstruction( "LD", "SP", "HL", new byte[] { 0xf9 } ),
                new ProcessorInstruction( "LD", "SP", "IX", new byte[] { 0xdd, 0xf9 } ),
                new ProcessorInstruction( "LD", "SP", "IY", new byte[] { 0xfd, 0xf9 } ),
                new ProcessorInstruction( "LD", "SP", "nn", new byte[] { 0x31, 0, 0 }, 1, 2 ),
                new ProcessorInstruction( "LD", "IXH", "n", new byte[] { 0xdd, 0x26, 0 }, 2, 1, true ),
                new ProcessorInstruction( "LD", "IXL", "n", new byte[] { 0xdd, 0x2e, 0 }, 2, 1, true ),
                new ProcessorInstruction( "LD", "B", "IXH", new byte[] { 0xdd, 0x44 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "B", "IXL", new byte[] { 0xdd, 0x45 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "C", "IXH", new byte[] { 0xdd, 0x4c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "C", "IXL", new byte[] { 0xdd, 0x4d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "D", "IXH", new byte[] { 0xdd, 0x54 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "D", "IXL", new byte[] { 0xdd, 0x55 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "E", "IXH", new byte[] { 0xdd, 0x5c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "E", "IXL", new byte[] { 0xdd, 0x5d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "B", new byte[] { 0xdd, 0x60 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "C", new byte[] { 0xdd, 0x61 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "D", new byte[] { 0xdd, 0x62 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "E", new byte[] { 0xdd, 0x63 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "IXH", new byte[] { 0xdd, 0x64 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "IXL", new byte[] { 0xdd, 0x65 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXH", "A", new byte[] { 0xdd, 0x67 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "B", new byte[] { 0xdd, 0x68 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "C", new byte[] { 0xdd, 0x69 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "D", new byte[] { 0xdd, 0x6a }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "E", new byte[] { 0xdd, 0x6b }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "IXH", new byte[] { 0xdd, 0x6c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "IXL", new byte[] { 0xdd, 0x6d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IXL", "A", new byte[] { 0xdd, 0x6f }, 0, 0, true ),
                new ProcessorInstruction( "LD", "A", "IXH", new byte[] { 0xdd, 0x7c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "A", "IXL", new byte[] { 0xdd, 0x7d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "n", new byte[] { 0xfd, 0x26, 0 }, 2, 1, true ),
                new ProcessorInstruction( "LD", "IYL", "n", new byte[] { 0xfd, 0x2e, 0 }, 2, 1, true ),
                new ProcessorInstruction( "LD", "B", "IYH", new byte[] { 0xfd, 0x44 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "B", "IYL", new byte[] { 0xfd, 0x45 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "C", "IYH", new byte[] { 0xfd, 0x4c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "C", "IYL", new byte[] { 0xfd, 0x4d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "D", "IYH", new byte[] { 0xfd, 0x54 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "D", "IYL", new byte[] { 0xfd, 0x55 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "E", "IYH", new byte[] { 0xfd, 0x5c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "E", "IYL", new byte[] { 0xfd, 0x5d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "B", new byte[] { 0xfd, 0x60 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "C", new byte[] { 0xfd, 0x61 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "D", new byte[] { 0xfd, 0x62 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "E", new byte[] { 0xfd, 0x63 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "IYH", new byte[] { 0xfd, 0x64 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "IYL", new byte[] { 0xfd, 0x65 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYH", "A", new byte[] { 0xfd, 0x67 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "B", new byte[] { 0xfd, 0x68 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "C", new byte[] { 0xfd, 0x69 }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "D", new byte[] { 0xfd, 0x6a }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "E", new byte[] { 0xfd, 0x6b }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "IYH", new byte[] { 0xfd, 0x6c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "IYL", new byte[] { 0xfd, 0x6d }, 0, 0, true ),
                new ProcessorInstruction( "LD", "IYL", "A", new byte[] { 0xfd, 0x6f }, 0, 0, true ),
                new ProcessorInstruction( "LD", "A", "IYH", new byte[] { 0xfd, 0x7c }, 0, 0, true ),
                new ProcessorInstruction( "LD", "A", "IYL", new byte[] { 0xfd, 0x7d }, 0, 0, true ) } },
            { "LDD", new ProcessorInstruction[] {
                new ProcessorInstruction( "LDD", null, null, new byte[] { 0xed, 0xa8 } ) } },
            { "LDDR", new ProcessorInstruction[] {
                new ProcessorInstruction( "LDDR", null, null, new byte[] { 0xed, 0xb8 } ) } },
            { "LDI", new ProcessorInstruction[] {
                new ProcessorInstruction( "LDI", null, null, new byte[] { 0xed, 0xa0 } ) } },
            { "LDIR", new ProcessorInstruction[] {
                new ProcessorInstruction( "LDIR", null, null, new byte[] { 0xed, 0xb0 } ) } },
            { "NEG", new ProcessorInstruction[] {
                new ProcessorInstruction( "NEG", null, null, new byte[] { 0xed, 0x44 } ) } },
            { "NOP", new ProcessorInstruction[] {
                new ProcessorInstruction( "NOP", null, null, new byte[] { 0x00 } ) } },
            { "OR", new ProcessorInstruction[] {
                new ProcessorInstruction( "OR", "(HL)", null, new byte[] { 0xb6 } ),
                new ProcessorInstruction( "OR", "(IX+n)", null, new byte[] { 0xdd, 0xb6, 0 }, 2, 1 ),
                new ProcessorInstruction( "OR", "(IY+n)", null, new byte[] { 0xfd, 0xb6, 0 }, 2, 1 ),
                new ProcessorInstruction( "OR", "A", null, new byte[] { 0xb7 } ),
                new ProcessorInstruction( "OR", "B", null, new byte[] { 0xb0 } ),
                new ProcessorInstruction( "OR", "C", null, new byte[] { 0xb1 } ),
                new ProcessorInstruction( "OR", "D", null, new byte[] { 0xb2 } ),
                new ProcessorInstruction( "OR", "E", null, new byte[] { 0xb3 } ),
                new ProcessorInstruction( "OR", "H", null, new byte[] { 0xb4 } ),
                new ProcessorInstruction( "OR", "L", null, new byte[] { 0xb5 } ),
                new ProcessorInstruction( "OR", "n", null, new byte[] { 0xf6, 0 }, 1, 1 ),
                new ProcessorInstruction( "OR", "IXH", null, new byte[] { 0xdd, 0xb4 }, 0, 0, true ),
                new ProcessorInstruction( "OR", "IXL", null, new byte[] { 0xdd, 0xb5 }, 0, 0, true ),
                new ProcessorInstruction( "OR", "IYH", null, new byte[] { 0xfd, 0xb4 }, 0, 0, true ),
                new ProcessorInstruction( "OR", "IYL", null, new byte[] { 0xfd, 0xb5 }, 0, 0, true ) } },
            { "OTDR", new ProcessorInstruction[] {
                new ProcessorInstruction( "OTDR", null, null, new byte[] { 0xed, 0xbb } ) } },
            { "OTIR", new ProcessorInstruction[] {
                new ProcessorInstruction( "OTIR", null, null, new byte[] { 0xed, 0xb3 } ) } },
            { "OUT", new ProcessorInstruction[] {
                new ProcessorInstruction( "OUT", "(C)", "A", new byte[] { 0xed, 0x79 } ),
                new ProcessorInstruction( "OUT", "(C)", "B", new byte[] { 0xed, 0x41 } ),
                new ProcessorInstruction( "OUT", "(C)", "C", new byte[] { 0xed, 0x49 } ),
                new ProcessorInstruction( "OUT", "(C)", "D", new byte[] { 0xed, 0x51 } ),
                new ProcessorInstruction( "OUT", "(C)", "E", new byte[] { 0xed, 0x59 } ),
                new ProcessorInstruction( "OUT", "(C)", "H", new byte[] { 0xed, 0x61 } ),
                new ProcessorInstruction( "OUT", "(C)", "L", new byte[] { 0xed, 0x69 } ),
                new ProcessorInstruction( "OUT", "(n)", "A", new byte[] { 0xd3, 0 }, 1, 1 ),
                new ProcessorInstruction( "OUT", "F", "(C)", new byte[] { 0xed, 0x71 }, 0, 0, true ) } },
            { "OUTD", new ProcessorInstruction[] {
                new ProcessorInstruction( "OUTD", null, null, new byte[] { 0xed, 0xab } ) } },
            { "OUTI", new ProcessorInstruction[] {
                new ProcessorInstruction( "OUTI", null, null, new byte[] { 0xed, 0xa3 } ) } },
            { "POP", new ProcessorInstruction[] {
                new ProcessorInstruction( "POP", "AF", null, new byte[] { 0xf1 } ),
                new ProcessorInstruction( "POP", "BC", null, new byte[] { 0xc1 } ),
                new ProcessorInstruction( "POP", "DE", null, new byte[] { 0xd1 } ),
                new ProcessorInstruction( "POP", "HL", null, new byte[] { 0xe1 } ),
                new ProcessorInstruction( "POP", "IX", null, new byte[] { 0xdd, 0xe1 } ),
                new ProcessorInstruction( "POP", "IY", null, new byte[] { 0xfd, 0xe1 } ) } },
            { "PUSH", new ProcessorInstruction[] {
                new ProcessorInstruction( "PUSH", "AF", null, new byte[] { 0xf5 } ),
                new ProcessorInstruction( "PUSH", "BC", null, new byte[] { 0xc5 } ),
                new ProcessorInstruction( "PUSH", "DE", null, new byte[] { 0xd5 } ),
                new ProcessorInstruction( "PUSH", "HL", null, new byte[] { 0xe5 } ),
                new ProcessorInstruction( "PUSH", "IX", null, new byte[] { 0xdd, 0xe5 } ),
                new ProcessorInstruction( "PUSH", "IY", null, new byte[] { 0xfd, 0xe5 } ) } },
            { "RES", new ProcessorInstruction[] {
                new ProcessorInstruction( "RES", "0", "(HL)", new byte[] { 0xcb, 0x86 } ),
                new ProcessorInstruction( "RES", "0", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x86 } ),
                new ProcessorInstruction( "RES", "0", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x86 } ),
                new ProcessorInstruction( "RES", "0", "A", new byte[] { 0xcb, 0x87 } ),
                new ProcessorInstruction( "RES", "0", "B", new byte[] { 0xcb, 0x80 } ),
                new ProcessorInstruction( "RES", "0", "C", new byte[] { 0xcb, 0x81 } ),
                new ProcessorInstruction( "RES", "0", "D", new byte[] { 0xcb, 0x82 } ),
                new ProcessorInstruction( "RES", "0", "E", new byte[] { 0xcb, 0x83 } ),
                new ProcessorInstruction( "RES", "0", "H", new byte[] { 0xcb, 0x84 } ),
                new ProcessorInstruction( "RES", "0", "L", new byte[] { 0xcb, 0x85 } ),
                new ProcessorInstruction( "RES", "1", "(HL)", new byte[] { 0xcb, 0x8e } ),
                new ProcessorInstruction( "RES", "1", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x8e } ),
                new ProcessorInstruction( "RES", "1", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x8e } ),
                new ProcessorInstruction( "RES", "1", "A", new byte[] { 0xcb, 0x8f } ),
                new ProcessorInstruction( "RES", "1", "B", new byte[] { 0xcb, 0x88 } ),
                new ProcessorInstruction( "RES", "1", "C", new byte[] { 0xcb, 0x89 } ),
                new ProcessorInstruction( "RES", "1", "D", new byte[] { 0xcb, 0x8a } ),
                new ProcessorInstruction( "RES", "1", "E", new byte[] { 0xcb, 0x8b } ),
                new ProcessorInstruction( "RES", "1", "H", new byte[] { 0xcb, 0x8c } ),
                new ProcessorInstruction( "RES", "1", "L", new byte[] { 0xcb, 0x8d } ),
                new ProcessorInstruction( "RES", "2", "(HL)", new byte[] { 0xcb, 0x96 } ),
                new ProcessorInstruction( "RES", "2", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x96 } ),
                new ProcessorInstruction( "RES", "2", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x96 } ),
                new ProcessorInstruction( "RES", "2", "A", new byte[] { 0xcb, 0x97 } ),
                new ProcessorInstruction( "RES", "2", "B", new byte[] { 0xcb, 0x90 } ),
                new ProcessorInstruction( "RES", "2", "C", new byte[] { 0xcb, 0x91 } ),
                new ProcessorInstruction( "RES", "2", "D", new byte[] { 0xcb, 0x92 } ),
                new ProcessorInstruction( "RES", "2", "E", new byte[] { 0xcb, 0x93 } ),
                new ProcessorInstruction( "RES", "2", "H", new byte[] { 0xcb, 0x94 } ),
                new ProcessorInstruction( "RES", "2", "L", new byte[] { 0xcb, 0x95 } ),
                new ProcessorInstruction( "RES", "3", "(HL)", new byte[] { 0xcb, 0x9e } ),
                new ProcessorInstruction( "RES", "3", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0x9e } ),
                new ProcessorInstruction( "RES", "3", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0x9e } ),
                new ProcessorInstruction( "RES", "3", "A", new byte[] { 0xcb, 0x9f } ),
                new ProcessorInstruction( "RES", "3", "B", new byte[] { 0xcb, 0x98 } ),
                new ProcessorInstruction( "RES", "3", "C", new byte[] { 0xcb, 0x99 } ),
                new ProcessorInstruction( "RES", "3", "D", new byte[] { 0xcb, 0x9a } ),
                new ProcessorInstruction( "RES", "3", "E", new byte[] { 0xcb, 0x9b } ),
                new ProcessorInstruction( "RES", "3", "H", new byte[] { 0xcb, 0x9c } ),
                new ProcessorInstruction( "RES", "3", "L", new byte[] { 0xcb, 0x9d } ),
                new ProcessorInstruction( "RES", "4", "(HL)", new byte[] { 0xcb, 0xa6 } ),
                new ProcessorInstruction( "RES", "4", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xa6 } ),
                new ProcessorInstruction( "RES", "4", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xa6 } ),
                new ProcessorInstruction( "RES", "4", "A", new byte[] { 0xcb, 0xa7 } ),
                new ProcessorInstruction( "RES", "4", "B", new byte[] { 0xcb, 0xa0 } ),
                new ProcessorInstruction( "RES", "4", "C", new byte[] { 0xcb, 0xa1 } ),
                new ProcessorInstruction( "RES", "4", "D", new byte[] { 0xcb, 0xa2 } ),
                new ProcessorInstruction( "RES", "4", "E", new byte[] { 0xcb, 0xa3 } ),
                new ProcessorInstruction( "RES", "4", "H", new byte[] { 0xcb, 0xa4 } ),
                new ProcessorInstruction( "RES", "4", "L", new byte[] { 0xcb, 0xa5 } ),
                new ProcessorInstruction( "RES", "5", "(HL)", new byte[] { 0xcb, 0xae } ),
                new ProcessorInstruction( "RES", "5", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xae } ),
                new ProcessorInstruction( "RES", "5", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xae } ),
                new ProcessorInstruction( "RES", "5", "A", new byte[] { 0xcb, 0xaf } ),
                new ProcessorInstruction( "RES", "5", "B", new byte[] { 0xcb, 0xa8 } ),
                new ProcessorInstruction( "RES", "5", "C", new byte[] { 0xcb, 0xa9 } ),
                new ProcessorInstruction( "RES", "5", "D", new byte[] { 0xcb, 0xaa } ),
                new ProcessorInstruction( "RES", "5", "E", new byte[] { 0xcb, 0xab } ),
                new ProcessorInstruction( "RES", "5", "H", new byte[] { 0xcb, 0xac } ),
                new ProcessorInstruction( "RES", "5", "L", new byte[] { 0xcb, 0xad } ),
                new ProcessorInstruction( "RES", "6", "(HL)", new byte[] { 0xcb, 0xb6 } ),
                new ProcessorInstruction( "RES", "6", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xb6 } ),
                new ProcessorInstruction( "RES", "6", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xb6 } ),
                new ProcessorInstruction( "RES", "6", "A", new byte[] { 0xcb, 0xb7 } ),
                new ProcessorInstruction( "RES", "6", "B", new byte[] { 0xcb, 0xb0 } ),
                new ProcessorInstruction( "RES", "6", "C", new byte[] { 0xcb, 0xb1 } ),
                new ProcessorInstruction( "RES", "6", "D", new byte[] { 0xcb, 0xb2 } ),
                new ProcessorInstruction( "RES", "6", "E", new byte[] { 0xcb, 0xb3 } ),
                new ProcessorInstruction( "RES", "6", "H", new byte[] { 0xcb, 0xb4 } ),
                new ProcessorInstruction( "RES", "6", "L", new byte[] { 0xcb, 0xb5 } ),
                new ProcessorInstruction( "RES", "7", "(HL)", new byte[] { 0xcb, 0xbe } ),
                new ProcessorInstruction( "RES", "7", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xbe } ),
                new ProcessorInstruction( "RES", "7", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xbe } ),
                new ProcessorInstruction( "RES", "7", "A", new byte[] { 0xcb, 0xbf } ),
                new ProcessorInstruction( "RES", "7", "B", new byte[] { 0xcb, 0xb8 } ),
                new ProcessorInstruction( "RES", "7", "C", new byte[] { 0xcb, 0xb9 } ),
                new ProcessorInstruction( "RES", "7", "D", new byte[] { 0xcb, 0xba } ),
                new ProcessorInstruction( "RES", "7", "E", new byte[] { 0xcb, 0xbb } ),
                new ProcessorInstruction( "RES", "7", "H", new byte[] { 0xcb, 0xbc } ),
                new ProcessorInstruction( "RES", "7", "L", new byte[] { 0xcb, 0xbd } ) } },
            { "RET", new ProcessorInstruction[] {
                new ProcessorInstruction( "RET", null, null, new byte[] { 0xc9 } ),
                new ProcessorInstruction( "RET", "C", null, new byte[] { 0xd8 } ),
                new ProcessorInstruction( "RET", "M", null, new byte[] { 0xf8 } ),
                new ProcessorInstruction( "RET", "nc", null, new byte[] { 0xd0 } ),
                new ProcessorInstruction( "RET", "nz", null, new byte[] { 0xc0 } ),
                new ProcessorInstruction( "RET", "P", null, new byte[] { 0xf0 } ),
                new ProcessorInstruction( "RET", "PE", null, new byte[] { 0xe8 } ),
                new ProcessorInstruction( "RET", "PO", null, new byte[] { 0xe0 } ),
                new ProcessorInstruction( "RET", "Z", null, new byte[] { 0xc8 } ) } },
            { "RETI", new ProcessorInstruction[] {
                new ProcessorInstruction( "RETI", null, null, new byte[] { 0xed, 0x4d } ) } },
            { "RETN", new ProcessorInstruction[] {
                new ProcessorInstruction( "RETN", null, null, new byte[] { 0xed, 0x45 } ) } },
            { "RL", new ProcessorInstruction[] {
                new ProcessorInstruction( "RL", "(HL)", null, new byte[] { 0xcb, 0x16 } ),
                new ProcessorInstruction( "RL", "A", null, new byte[] { 0xcb, 0x17 } ),
                new ProcessorInstruction( "RL", "B", null, new byte[] { 0xcb, 0x10 } ),
                new ProcessorInstruction( "RL", "C", null, new byte[] { 0xcb, 0x11 } ),
                new ProcessorInstruction( "RL", "D", null, new byte[] { 0xcb, 0x12 } ),
                new ProcessorInstruction( "RL", "E", null, new byte[] { 0xcb, 0x13 } ),
                new ProcessorInstruction( "RL", "H", null, new byte[] { 0xcb, 0x14 } ),
                new ProcessorInstruction( "RL", "L", null, new byte[] { 0xcb, 0x15 } ),
                new ProcessorInstruction( "RL", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x16 } ),
                new ProcessorInstruction( "RL", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x16 } ) } },
            { "RLA", new ProcessorInstruction[] {
                new ProcessorInstruction( "RLA", null, null, new byte[] { 0x17 } ) } },
            { "RLC", new ProcessorInstruction[] {
                new ProcessorInstruction( "RLC", "(HL)", null, new byte[] { 0xcb, 0x06 } ),
                new ProcessorInstruction( "RLC", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x06 } ),
                new ProcessorInstruction( "RLC", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x06 } ),
                new ProcessorInstruction( "RLC", "A", null, new byte[] { 0xcb, 0x07 } ),
                new ProcessorInstruction( "RLC", "B", null, new byte[] { 0xcb, 0x00 } ),
                new ProcessorInstruction( "RLC", "C", null, new byte[] { 0xcb, 0x01 } ),
                new ProcessorInstruction( "RLC", "D", null, new byte[] { 0xcb, 0x02 } ),
                new ProcessorInstruction( "RLC", "E", null, new byte[] { 0xcb, 0x03 } ),
                new ProcessorInstruction( "RLC", "H", null, new byte[] { 0xcb, 0x04 } ),
                new ProcessorInstruction( "RLC", "L", null, new byte[] { 0xcb, 0x05 } ) } },
            { "RLCA", new ProcessorInstruction[] {
                new ProcessorInstruction( "RLCA", null, null, new byte[] { 0x07 } ) } },
            { "RLD", new ProcessorInstruction[] {
                new ProcessorInstruction( "RLD", null, null, new byte[] { 0xed, 0x6f } ) } },
            { "RR", new ProcessorInstruction[] {
                new ProcessorInstruction( "RR", "(HL)", null, new byte[] { 0xcb, 0x1e } ),
                new ProcessorInstruction( "RR", "A", null, new byte[] { 0xcb, 0x1f } ),
                new ProcessorInstruction( "RR", "B", null, new byte[] { 0xcb, 0x18 } ),
                new ProcessorInstruction( "RR", "C", null, new byte[] { 0xcb, 0x19 } ),
                new ProcessorInstruction( "RR", "D", null, new byte[] { 0xcb, 0x1a } ),
                new ProcessorInstruction( "RR", "E", null, new byte[] { 0xcb, 0x1b } ),
                new ProcessorInstruction( "RR", "H", null, new byte[] { 0xcb, 0x1c } ),
                new ProcessorInstruction( "RR", "L", null, new byte[] { 0xcb, 0x1d } ),
                new ProcessorInstruction( "RR", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x1e } ),
                new ProcessorInstruction( "RR", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x1e } ) } },
            { "RRA", new ProcessorInstruction[] {
                new ProcessorInstruction( "RRA", null, null, new byte[] { 0x1f } ) } },
            { "RRC", new ProcessorInstruction[] {
                new ProcessorInstruction( "RRC", "(HL)", null, new byte[] { 0xcb, 0x0e } ),
                new ProcessorInstruction( "RRC", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x0e } ),
                new ProcessorInstruction( "RRC", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x0e } ),
                new ProcessorInstruction( "RRC", "A", null, new byte[] { 0xcb, 0x0f } ),
                new ProcessorInstruction( "RRC", "B", null, new byte[] { 0xcb, 0x08 } ),
                new ProcessorInstruction( "RRC", "C", null, new byte[] { 0xcb, 0x09 } ),
                new ProcessorInstruction( "RRC", "D", null, new byte[] { 0xcb, 0x0a } ),
                new ProcessorInstruction( "RRC", "E", null, new byte[] { 0xcb, 0x0b } ),
                new ProcessorInstruction( "RRC", "H", null, new byte[] { 0xcb, 0x0c } ),
                new ProcessorInstruction( "RRC", "L", null, new byte[] { 0xcb, 0x0d } ) } },
            { "RRCA", new ProcessorInstruction[] {
                new ProcessorInstruction( "RRCA", null, null, new byte[] { 0x0f } ) } },
            { "RRD", new ProcessorInstruction[] {
                new ProcessorInstruction( "RRD", null, null, new byte[] { 0xed, 0x67 } ) } },
            { "RST", new ProcessorInstruction[] {
                new ProcessorInstruction( "RST", "00H", null, new byte[] { 0xc7 } ),
                new ProcessorInstruction( "RST", "10H", null, new byte[] { 0xd7 } ),
                new ProcessorInstruction( "RST", "18H", null, new byte[] { 0xdf } ),
                new ProcessorInstruction( "RST", "20H", null, new byte[] { 0xe7 } ),
                new ProcessorInstruction( "RST", "28H", null, new byte[] { 0xef } ),
                new ProcessorInstruction( "RST", "30H", null, new byte[] { 0xf7 } ),
                new ProcessorInstruction( "RST", "38H", null, new byte[] { 0xff } ),
                new ProcessorInstruction( "RST", "08H", null, new byte[] { 0xcf } ) } },
            { "SBC", new ProcessorInstruction[] {
                new ProcessorInstruction( "SBC", "(HL)", null, new byte[] { 0x9e } ),
                new ProcessorInstruction( "SBC", "A", null, new byte[] { 0x9f } ),
                new ProcessorInstruction( "SBC", "A", "(IX+n)", new byte[] { 0xdd, 0x9e, 0 }, 2, 1 ),
                new ProcessorInstruction( "SBC", "A", "(IY+n)", new byte[] { 0xfd, 0x9e, 0 }, 2, 1 ),
                new ProcessorInstruction( "SBC", "A", "n", new byte[] { 0xde, 0 }, 1, 1 ),
                new ProcessorInstruction( "SBC", "B", null, new byte[] { 0x98 } ),
                new ProcessorInstruction( "SBC", "C", null, new byte[] { 0x99 } ),
                new ProcessorInstruction( "SBC", "D", null, new byte[] { 0x9a } ),
                new ProcessorInstruction( "SBC", "E", null, new byte[] { 0x9b } ),
                new ProcessorInstruction( "SBC", "H", null, new byte[] { 0x9c } ),
                new ProcessorInstruction( "SBC", "HL", "BC", new byte[] { 0xed, 0x42 } ),
                new ProcessorInstruction( "SBC", "HL", "DE", new byte[] { 0xed, 0x52 } ),
                new ProcessorInstruction( "SBC", "HL", "HL", new byte[] { 0xed, 0x62 } ),
                new ProcessorInstruction( "SBC", "HL", "SP", new byte[] { 0xed, 0x72 } ),
                new ProcessorInstruction( "SBC", "L", null, new byte[] { 0x9d } ),
                new ProcessorInstruction( "SBC", "A", "IXH", new byte[] { 0xdd, 0x9c }, 0, 0, true ),
                new ProcessorInstruction( "SBC", "A", "IXL", new byte[] { 0xdd, 0x9d }, 0, 0, true ),
                new ProcessorInstruction( "SBC", "A", "IYH", new byte[] { 0xfd, 0x9c }, 0, 0, true ),
                new ProcessorInstruction( "SBC", "A", "IYL", new byte[] { 0xfd, 0x9d }, 0, 0, true ) } },
            { "SCF", new ProcessorInstruction[] {
                new ProcessorInstruction( "SCF", null, null, new byte[] { 0x37 } ) } },
            { "SET", new ProcessorInstruction[] {
                new ProcessorInstruction( "SET", "0", "(HL)", new byte[] { 0xcb, 0xc6 } ),
                new ProcessorInstruction( "SET", "0", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xc6 } ),
                new ProcessorInstruction( "SET", "0", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xc6 } ),
                new ProcessorInstruction( "SET", "0", "A", new byte[] { 0xcb, 0xc7 } ),
                new ProcessorInstruction( "SET", "0", "B", new byte[] { 0xcb, 0xc0 } ),
                new ProcessorInstruction( "SET", "0", "C", new byte[] { 0xcb, 0xc1 } ),
                new ProcessorInstruction( "SET", "0", "D", new byte[] { 0xcb, 0xc2 } ),
                new ProcessorInstruction( "SET", "0", "E", new byte[] { 0xcb, 0xc3 } ),
                new ProcessorInstruction( "SET", "0", "H", new byte[] { 0xcb, 0xc4 } ),
                new ProcessorInstruction( "SET", "0", "L", new byte[] { 0xcb, 0xc5 } ),
                new ProcessorInstruction( "SET", "1", "(HL)", new byte[] { 0xcb, 0xce } ),
                new ProcessorInstruction( "SET", "1", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xce } ),
                new ProcessorInstruction( "SET", "1", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xce } ),
                new ProcessorInstruction( "SET", "1", "A", new byte[] { 0xcb, 0xcf } ),
                new ProcessorInstruction( "SET", "1", "B", new byte[] { 0xcb, 0xc8 } ),
                new ProcessorInstruction( "SET", "1", "C", new byte[] { 0xcb, 0xc9 } ),
                new ProcessorInstruction( "SET", "1", "D", new byte[] { 0xcb, 0xca } ),
                new ProcessorInstruction( "SET", "1", "E", new byte[] { 0xcb, 0xcb } ),
                new ProcessorInstruction( "SET", "1", "H", new byte[] { 0xcb, 0xcc } ),
                new ProcessorInstruction( "SET", "1", "L", new byte[] { 0xcb, 0xcd } ),
                new ProcessorInstruction( "SET", "2", "(HL)", new byte[] { 0xcb, 0xd6 } ),
                new ProcessorInstruction( "SET", "2", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xd6 } ),
                new ProcessorInstruction( "SET", "2", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xd6 } ),
                new ProcessorInstruction( "SET", "2", "A", new byte[] { 0xcb, 0xd7 } ),
                new ProcessorInstruction( "SET", "2", "B", new byte[] { 0xcb, 0xd0 } ),
                new ProcessorInstruction( "SET", "2", "C", new byte[] { 0xcb, 0xd1 } ),
                new ProcessorInstruction( "SET", "2", "D", new byte[] { 0xcb, 0xd2 } ),
                new ProcessorInstruction( "SET", "2", "E", new byte[] { 0xcb, 0xd3 } ),
                new ProcessorInstruction( "SET", "2", "H", new byte[] { 0xcb, 0xd4 } ),
                new ProcessorInstruction( "SET", "2", "L", new byte[] { 0xcb, 0xd5 } ),
                new ProcessorInstruction( "SET", "3", "(HL)", new byte[] { 0xcb, 0xde } ),
                new ProcessorInstruction( "SET", "3", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xde } ),
                new ProcessorInstruction( "SET", "3", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xde } ),
                new ProcessorInstruction( "SET", "3", "A", new byte[] { 0xcb, 0xdf } ),
                new ProcessorInstruction( "SET", "3", "B", new byte[] { 0xcb, 0xd8 } ),
                new ProcessorInstruction( "SET", "3", "C", new byte[] { 0xcb, 0xd9 } ),
                new ProcessorInstruction( "SET", "3", "D", new byte[] { 0xcb, 0xda } ),
                new ProcessorInstruction( "SET", "3", "E", new byte[] { 0xcb, 0xdb } ),
                new ProcessorInstruction( "SET", "3", "H", new byte[] { 0xcb, 0xdc } ),
                new ProcessorInstruction( "SET", "3", "L", new byte[] { 0xcb, 0xdd } ),
                new ProcessorInstruction( "SET", "4", "(HL)", new byte[] { 0xcb, 0xe6 } ),
                new ProcessorInstruction( "SET", "4", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xe6 } ),
                new ProcessorInstruction( "SET", "4", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xe6 } ),
                new ProcessorInstruction( "SET", "4", "A", new byte[] { 0xcb, 0xe7 } ),
                new ProcessorInstruction( "SET", "4", "B", new byte[] { 0xcb, 0xe0 } ),
                new ProcessorInstruction( "SET", "4", "C", new byte[] { 0xcb, 0xe1 } ),
                new ProcessorInstruction( "SET", "4", "D", new byte[] { 0xcb, 0xe2 } ),
                new ProcessorInstruction( "SET", "4", "E", new byte[] { 0xcb, 0xe3 } ),
                new ProcessorInstruction( "SET", "4", "H", new byte[] { 0xcb, 0xe4 } ),
                new ProcessorInstruction( "SET", "4", "L", new byte[] { 0xcb, 0xe5 } ),
                new ProcessorInstruction( "SET", "5", "(HL)", new byte[] { 0xcb, 0xee } ),
                new ProcessorInstruction( "SET", "5", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xee } ),
                new ProcessorInstruction( "SET", "5", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xee } ),
                new ProcessorInstruction( "SET", "5", "A", new byte[] { 0xcb, 0xef } ),
                new ProcessorInstruction( "SET", "5", "B", new byte[] { 0xcb, 0xe8 } ),
                new ProcessorInstruction( "SET", "5", "C", new byte[] { 0xcb, 0xe9 } ),
                new ProcessorInstruction( "SET", "5", "D", new byte[] { 0xcb, 0xea } ),
                new ProcessorInstruction( "SET", "5", "E", new byte[] { 0xcb, 0xeb } ),
                new ProcessorInstruction( "SET", "5", "H", new byte[] { 0xcb, 0xec } ),
                new ProcessorInstruction( "SET", "5", "L", new byte[] { 0xcb, 0xed } ),
                new ProcessorInstruction( "SET", "6", "(HL)", new byte[] { 0xcb, 0xf6 } ),
                new ProcessorInstruction( "SET", "6", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xf6 } ),
                new ProcessorInstruction( "SET", "6", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xf6 } ),
                new ProcessorInstruction( "SET", "6", "A", new byte[] { 0xcb, 0xf7 } ),
                new ProcessorInstruction( "SET", "6", "B", new byte[] { 0xcb, 0xf0 } ),
                new ProcessorInstruction( "SET", "6", "C", new byte[] { 0xcb, 0xf1 } ),
                new ProcessorInstruction( "SET", "6", "D", new byte[] { 0xcb, 0xf2 } ),
                new ProcessorInstruction( "SET", "6", "E", new byte[] { 0xcb, 0xf3 } ),
                new ProcessorInstruction( "SET", "6", "H", new byte[] { 0xcb, 0xf4 } ),
                new ProcessorInstruction( "SET", "6", "L", new byte[] { 0xcb, 0xf5 } ),
                new ProcessorInstruction( "SET", "7", "(HL)", new byte[] { 0xcb, 0xfe } ),
                new ProcessorInstruction( "SET", "7", "(IX+n)", new byte[] { 0xdd, 0xcb, 0, 0xfe } ),
                new ProcessorInstruction( "SET", "7", "(IY+n)", new byte[] { 0xfd, 0xcb, 0, 0xfe } ),
                new ProcessorInstruction( "SET", "7", "A", new byte[] { 0xcb, 0xff } ),
                new ProcessorInstruction( "SET", "7", "B", new byte[] { 0xcb, 0xf8 } ),
                new ProcessorInstruction( "SET", "7", "C", new byte[] { 0xcb, 0xf9 } ),
                new ProcessorInstruction( "SET", "7", "D", new byte[] { 0xcb, 0xfa } ),
                new ProcessorInstruction( "SET", "7", "E", new byte[] { 0xcb, 0xfb } ),
                new ProcessorInstruction( "SET", "7", "H", new byte[] { 0xcb, 0xfc } ),
                new ProcessorInstruction( "SET", "7", "L", new byte[] { 0xcb, 0xfd } ) } },
            { "SLA", new ProcessorInstruction[] {
                new ProcessorInstruction( "SLA", "(HL)", null, new byte[] { 0xcb, 0x26 } ),
                new ProcessorInstruction( "SLA", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x26 } ),
                new ProcessorInstruction( "SLA", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x26 } ),
                new ProcessorInstruction( "SLA", "A", null, new byte[] { 0xcb, 0x27 } ),
                new ProcessorInstruction( "SLA", "B", null, new byte[] { 0xcb, 0x20 } ),
                new ProcessorInstruction( "SLA", "C", null, new byte[] { 0xcb, 0x21 } ),
                new ProcessorInstruction( "SLA", "D", null, new byte[] { 0xcb, 0x22 } ),
                new ProcessorInstruction( "SLA", "E", null, new byte[] { 0xcb, 0x23 } ),
                new ProcessorInstruction( "SLA", "H", null, new byte[] { 0xcb, 0x24 } ),
                new ProcessorInstruction( "SLA", "L", null, new byte[] { 0xcb, 0x25 } ) } },
            { "SRA", new ProcessorInstruction[] {
                new ProcessorInstruction( "SRA", "(HL)", null, new byte[] { 0xcb, 0x2e } ),
                new ProcessorInstruction( "SRA", "(IX+n)", null, new byte[] { 0xdd, 0xcb, 0, 0x2e } ),
                new ProcessorInstruction( "SRA", "(IY+n)", null, new byte[] { 0xfd, 0xcb, 0, 0x2e } ),
                new ProcessorInstruction( "SRA", "A", null, new byte[] { 0xcb, 0x2f } ),
                new ProcessorInstruction( "SRA", "B", null, new byte[] { 0xcb, 0x28 } ),
                new ProcessorInstruction( "SRA", "C", null, new byte[] { 0xcb, 0x29 } ),
                new ProcessorInstruction( "SRA", "D", null, new byte[] { 0xcb, 0x2a } ),
                new ProcessorInstruction( "SRA", "E", null, new byte[] { 0xcb, 0x2b } ),
                new ProcessorInstruction( "SRA", "H", null, new byte[] { 0xcb, 0x2c } ),
                new ProcessorInstruction( "SRA", "L", null, new byte[] { 0xcb, 0x2d } ) } },
            { "SRL", new ProcessorInstruction[] {
                new ProcessorInstruction( "SRL", "(HL)", null, new byte[] { 0xcb, 0x3e } ),
                new ProcessorInstruction( "SRL", "A", null, new byte[] { 0xcb, 0x3f } ),
                new ProcessorInstruction( "SRL", "B", null, new byte[] { 0xcb, 0x38 } ),
                new ProcessorInstruction( "SRL", "C", null, new byte[] { 0xcb, 0x39 } ),
                new ProcessorInstruction( "SRL", "D", null, new byte[] { 0xcb, 0x3a } ),
                new ProcessorInstruction( "SRL", "E", null, new byte[] { 0xcb, 0x3b } ),
                new ProcessorInstruction( "SRL", "H", null, new byte[] { 0xcb, 0x3c } ),
                new ProcessorInstruction( "SRL", "L", null, new byte[] { 0xcb, 0x3d } ) } },
            { "SUB", new ProcessorInstruction[] {
                new ProcessorInstruction( "SUB", "(HL)", null, new byte[] { 0x96 } ),
                new ProcessorInstruction( "SUB", "(IX+n)", null, new byte[] { 0xdd, 0x96, 0 }, 2, 1 ),
                new ProcessorInstruction( "SUB", "(IY+n)", null, new byte[] { 0xfd, 0x96, 0 }, 2, 1 ),
                new ProcessorInstruction( "SUB", "A", null, new byte[] { 0x97 } ),
                new ProcessorInstruction( "SUB", "B", null, new byte[] { 0x90 } ),
                new ProcessorInstruction( "SUB", "C", null, new byte[] { 0x91 } ),
                new ProcessorInstruction( "SUB", "D", null, new byte[] { 0x92 } ),
                new ProcessorInstruction( "SUB", "E", null, new byte[] { 0x93 } ),
                new ProcessorInstruction( "SUB", "H", null, new byte[] { 0x94 } ),
                new ProcessorInstruction( "SUB", "L", null, new byte[] { 0x95 } ),
                new ProcessorInstruction( "SUB", "n", null, new byte[] { 0xd6, 0 }, 1, 1 ),
                new ProcessorInstruction( "SUB", "IXH", null, new byte[] { 0xdd, 0x94 }, 0, 0, true ),
                new ProcessorInstruction( "SUB", "IXL", null, new byte[] { 0xdd, 0x95 }, 0, 0, true ),
                new ProcessorInstruction( "SUB", "IYH", null, new byte[] { 0xfd, 0x94 }, 0, 0, true ),
                new ProcessorInstruction( "SUB", "IYL", null, new byte[] { 0xfd, 0x95 }, 0, 0, true ) } },
            { "XOR", new ProcessorInstruction[] {
                new ProcessorInstruction( "XOR", "(HL)", null, new byte[] { 0xae } ),
                new ProcessorInstruction( "XOR", "(IX+n)", null, new byte[] { 0xdd, 0xae, 0 }, 2, 1 ),
                new ProcessorInstruction( "XOR", "(IY+n)", null, new byte[] { 0xfd, 0xae, 0 }, 2, 1 ),
                new ProcessorInstruction( "XOR", "A", null, new byte[] { 0xaf } ),
                new ProcessorInstruction( "XOR", "B", null, new byte[] { 0xa8 } ),
                new ProcessorInstruction( "XOR", "C", null, new byte[] { 0xa9 } ),
                new ProcessorInstruction( "XOR", "D", null, new byte[] { 0xaa } ),
                new ProcessorInstruction( "XOR", "E", null, new byte[] { 0xab } ),
                new ProcessorInstruction( "XOR", "H", null, new byte[] { 0xac } ),
                new ProcessorInstruction( "XOR", "L", null, new byte[] { 0xad } ),
                new ProcessorInstruction( "XOR", "n", null, new byte[] { 0xee, 0 }, 1, 1 ),
                new ProcessorInstruction( "XOR", "IXH", null, new byte[] { 0xdd, 0xac }, 0, 0, true ),
                new ProcessorInstruction( "XOR", "IXL", null, new byte[] { 0xdd, 0xad }, 0, 0, true ),
                new ProcessorInstruction( "XOR", "IYH", null, new byte[] { 0xfd, 0xac }, 0, 0, true ),
                new ProcessorInstruction( "XOR", "IYL", null, new byte[] { 0xfd, 0xad }, 0, 0, true ) } },
            { "SLL", new ProcessorInstruction[] {
                new ProcessorInstruction( "SLL", "B", null, new byte[] { 0xcb, 0x30 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "C", null, new byte[] { 0xcb, 0x31 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "D", null, new byte[] { 0xcb, 0x32 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "E", null, new byte[] { 0xcb, 0x33 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "H", null, new byte[] { 0xcb, 0x34 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "L", null, new byte[] { 0xcb, 0x35 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "(HL)", null, new byte[] { 0xcb, 0x36 }, 0, 0, true ),
                new ProcessorInstruction( "SLL", "A", null, new byte[] { 0xcb, 0x37 }, 0, 0, true ) } }
        };
    }
}
