name: Build

on:
  push:
    branches:
    - github-actions
    - master
    tags:
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build
      working-directory: ./N80
      env:
        IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') && 'true' || '' }}
      run: |
        ./build.sh
        if [ -n "$IS_RELEASE" ]; then
          ./zip.sh
        fi
    - name: Publish artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: N80/Release/zips/*.zip
        tag: ${{ github.ref }}
        overwrite: true
